### ISSUE TITLE
Model' object has no attribute '_call_spec

### ISSUE THREAD

**Issue by Mayur79** [ianforme/face-prediction#3]
Model' object has no attribute '_call_spec'
  File "C:\Users\mayur_iyd6xcu\OneDrive\Desktop\Python\models\facepred.py", line 41, in detect_face
    sex_preds = sex_model.predict(center_img.reshape(1,224,224,3))[0][0]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur_iyd6xcu\OneDrive\Desktop\Python\models\facepred.py", line 73, in <module>
    face_locations = detect_face(rgb_frame)
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Model' object has no attribute '_call_spec'

**Comment by Arief-netizen** [comment]
try this:

!pip uninstall segmentation-models -y
!pip uninstall tensorflow -y
!pip uninstall keras -y
!pip uninstall tensorflow-estimator -y
!pip uninstall mtcnn -y

!pip install -U -q segmentation-models
!pip install -q tensorflow==2.2
!pip install -q keras==2.3.1
!pip install -q tensorflow-estimator==2.2
!pip install mtcnn
